### ISSUE TITLE
Automate the process of updating the Homebrew formula

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/xctools#11]
## Context
We currently update the homebrew formula manually when the version of xcode is bumped.

## What
Update the `Rakefile` to update the formula automatically as part of the release process.

**Comment by alpreu** [comment]
I'd like to work on this :)
Do you mean the 'url' part of the formula?

**Comment by yonaskolb** [comment]
Nice @alpreu!
Both the url and sha256 need to be updated.

```
url "https://github.com/xcodeswift/xcode/archive/0.1.0.tar.gz"
sha256 "827a26e09e961c4928bf45517ec9a864a4151c2903a281ed31df81a8030742d5"
```

You can get the sha256 of a file by running the following command
```
shasum -a 256 filename.tar.gz
```

**Comment by pepibumur** [comment]
That's great @alpreu. As @yonaskolb pointed out, both attributes need to be updated. The `.tar.gz` that you apply the hash to contains all the project files.

**Comment by alpreu** [comment]
Hi guys, I got a question. 
The archive needs to be created before calculating the hash, did you previously do this step manually with `tar -zxvf version.tar.gz` or am I missing some step when building?

**Comment by pepibumur** [comment]
What we did was getting the `tar.gz` from GitHub because it generates it for you. I think we should do sort of the same, but automated. When we release a new version:
- We push the new tag to GitHub.
- We get the `.tar.gz` using the url format `https://github.com/xcodeswift/xcode/archive/x.y.z.tar.gz`.
- We calculate the hash and update the formula accordingly.

If you wanted to do it by generating the `.tar.gz` locally, you'd have to remove the `.git` folder as well as all the elements that are gitignored.  Even with that, I'm not sure if we'd get the same `.tar.gz` that GitHub generates.
